version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    working_directory: /home/ubuntu/useradm
    steps:
      - checkout
      - run: apt-get update && apt-get install libldap2-dev libsasl2-dev -y
      - run: pip install -r requirements.txt
      - store_artifacts:
          path: test-reports/coverage
          destination: reports
      - store_test_results:
          path: "test-reports/"
